### PR TITLE
Incorrect float type for asynchronous_metrics were fixed

### PR DESCRIPTION
**Pull request by solyard**
Fixed incorrect  type for metrics value by issue #44

### CODE REVIEW

**Comment by Yanbuc** [comment]
toInt() function is error in http interface to query clickhouse. Try to use toInt64() maybe more fit
select metric, toInt64(value) from system.asynchronous_metrics

**Comment by solyard** [comment]
> toInt() function is error in http interface to query clickhouse. Try to use toInt64() maybe more fit
> select metric, toInt64(value) from system.asynchronous_metrics

I already use `toInt64(value)` in my PR

**Comment by Yanbuc** [comment]
> > toInt() function is error in http interface to query clickhouse. Try to use toInt64() maybe more fit
> > select metric, toInt64(value) from system.asynchronous_metrics
> 
> I already use `toInt64(value)` in my PR

Sorry! I didn't see carefully. Can I ask a querstion? Why the program has a exporter but import github.com/Percona-Lab/clickhouse_exporter/exporter. this bug not solved in github.com/Percona-Lab/clickhouse_exporter/exporter. Thank you

**Comment by solyard** [comment]
@Slach please check out the PR

**Comment by Slach** [comment]
@solyard sorry, I don't sure toInt is a good idea how to fix this behavior

**Comment by solyard** [comment]
> @solyard sorry, I don't sure toInt is a good idea how to fix this behavior

Will try to get another way for this. Thanks for feedback!

**Pull request closed without merging**
