### PR TITLE
Replace all hyphens with underscores in metrics

### LINKED ISSUE #66: hyphens in metric names causing scrape failures
In the latest clickhouse version, clickhouse is exporting metrics about devices, and this is generating metric names with hyphens in them, which are not valid for prometheus and scraping fails

```
# HELP clickhouse_block_active_time_dm-0 Number of BlockActiveTime_dm-0 async processed
# TYPE clickhouse_block_active_time_dm-0 gauge
```

### PR DESCRIPTION
**Pull request by jpiper**
Fixes #66

### CODE REVIEW

**Comment by jpiper** [comment]
I cannot sign the CLA at this time.

**Comment by alexey-milovidov** [comment]
Thank you! Technically there is only one possible solution for this task, so I just resubmitted it.

**Comment by alexey-milovidov** [comment]
Could you please share some information - why signing the CLA is impossible?
Is it some policy from your employer? How it's motivated?

**Comment by jpiper** [comment]
Yes, just that I would need to get approval from legal in order to sign this, which doesn't happen quickly!

**Pull request closed without merging**
